### ISSUE TITLE
Add senders list to unopened bundle

### ISSUE THREAD

**Issue by teresa-ou** [teresa-ou/inboxy#6]
User feedback:

"I think Inbox also listed the names of the senders next to the bundle title (when the bundle is not open)"

**Comment by teresa-ou** [comment]
This is now fixed in v1.2.0.

**Comment by benoror** [comment]
Hi! Collapsed bundles in **Inbundly** still show sender previews next to the title (Inbox-style). Truncation quirks can remain (#16 family).

If the preview is too thin for you, open an enhancement. Also new: **sender bundles** for unlabeled mail.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Site: https://inbundly.com/
